[tool.poetry]
name = "monitoring-agent"
version = "0.1.0"
description = ""
authors = ["517ANT39 <toni.tashchilin@inbox.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
